### PR TITLE
belinda_nestjs-02-39-forgot_password_controller

### LINKED ISSUE #39: forgot-password controller creation
Create a forgot-password controller that creates the endpoint.
[http://localhost:3000/api/auth/forgot-password](http://localhost:3000/api/auth/forgot-password)

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #39 
Create a forgot password controller in the auth module

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Yes, it works!
Screenshot 2023-11-02 at 7 53 12 PM
Screenshot 2023-11-02 at 7 53 38 PM

**Review by CourtneyHoppus — DISMISSED** [review]
I was able to recreate the testing that Taylor did, everything worked as expected.
A valid email returned a new token.
An invalid email threw the appropriate exception.
Sending an invalid email or not sending an email returned the appropriate prompts from class-validator.

**Comment by taylorpapke** [comment]
@tinpham5614 I think we can fix the merge conflict and close/open PR to retrigger CI

**Review by taylorpapke — APPROVED** [review]

**Review by Robel-003 — APPROVED** [review]
This looks great! And it's working, a valid email returns a new token while an invalid email returns the proper unauthorized exception.

**Review by CourtneyHoppus — APPROVED** [review]
Re-review of this PR.
I was able to recreate the testing that Taylor did, everything worked as expected.
A valid email returned a new token.
An invalid email threw the appropriate exception.
Sending an invalid email or not sending an email returned the appropriate prompts from class-validator.

**Pull request merged**
