### PR TITLE
belindas-closet-nestjs _1_21_refactor-product-console.log

### LINKED ISSUE #21: Refactor product console.log to use logger
As a backend developer, I will want to enable logging to view important information about the data transactions occurring.

**Is your feature request related to a problem? Please describe.**\
I'm always frustrated when I can't see why something is not working and console.logs are not completely cutting it.

**Describe the solution you'd like**\
Logs that will more accurately depict what is happening with the data.

**Include link(s) to relevant tutorial(s)**\
https://docs.nestjs.com/techniques/logger

**Describe alternatives you've considered**\
None.

**Is this issue related to any other issues?**\
This issue relates to issue #17 

**Additional context**\

Image

**Story Points**\
2-4 story points

### PR DESCRIPTION
**Pull request by CourtneyHoppus**
Resolves #21 

I have installed Winston and set up a logger for the project.
The logger is customized for the development environment and the production environment.

Looking for review if this is what the team would like.

To test:

- Pull the branch and run `npm install` or `yarn install` depending on your package manager.
- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid `MONGODB_URI` string for a database connection.
- You must set the `JWT_SECRET` to 'jwt'.
- Using the available API calls in the `ProductController`, use CURL or Postman to test.
- \* Some calls may require a valid JWT_TOKEN

Here is a screenshot of the logging output:

Logging output

Resources used:
This [article](https://reflectoring.io/node-logging-winston/) and this [article](https://betterstack.com/community/guides/logging/how-to-install-setup-and-use-winston-and-morgan-to-log-node-js-applications/) gave a nice overview.
This [article](https://timothy.hashnode.dev/advance-your-nestjs-application-with-winston-logger-a-step-by-step-guide) was what I based my work on.

### CODE REVIEW

**Comment by brinkbrink** [comment]
Looks good at a glance but I'll play around with it later before I leave an approval. What do y'all think? @theGaryLarson @tinpham5614

**Comment by tinpham5614** [comment]
Here is what I received when manually testing it:
Screenshot 2023-10-25 222951
I'm not sure if this format meets our expectations. Would the user module format be better?

**Comment by CourtneyHoppus** [comment]
@tinpham5614 as comment on the User Refactor PR, this format is a custom format we can change to however we would want it to look, this PR has the custom logger creator and included in app.module and main. Happy to adjust the format or revert the project to the built in logging.

**Comment by CourtneyHoppus** [comment]
Thanks for clarifying @taylorpapke, I took it for granted that in order to run the app you need the JWT_SECRET as that was in the [instructions](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) for running this app.

I forgot to add when anyone adds updates to the `package-lock.json` and the `package.json` when you pull the branch, you need to run `npm install`  and it will look for what needs to be installed. Thanks, you did it by installing winston directly.

**Review by taylorpapke — DISMISSED** [review]
Seems to be working great! I found 7 of the 8 logs but I wasn’t clever enough to figure out a way to produce an error for posting a new product.
get all error:
Screenshot 2023-10-26 at 3 07 40 AM
post success:
Screenshot 2023-10-26 at 3 18 06 AM
get find by id success:
Screenshot 2023-10-26 at 3 21 26 AM
get find by id error:
Screenshot 2023-10-26 at 3 35 08 AM
put update success:
Screenshot 2023-10-26 at 3 30 16 AM
get all success:
Screenshot 2023-10-26 at 3 36 50 AM
put update error:
Screenshot 2023-10-26 at 3 34 01 AM

**Comment by tinpham5614** [comment]
> @tinpham5614 as comment on the [User Refactor PR](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/33), this format is a custom format we can change to however we would want it to look, this PR has the custom logger creator and included in app.module and main. Happy to adjust the format or revert my work to the built in logging.

I believe this topic is important to discuss in order to determine the format for both apps. Thank you.

**Comment by CourtneyHoppus** [comment]
I noticed that the Product object wasn't outputting as a string, so I pushed some changes so that the Product will now pretty print as JSON in the log.

**Comment by taylorpapke** [comment]
Cool, I think I can see that now:
Screenshot 2023-10-27 at 2 17 18 AM

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
