### PR TITLE
Database integration for user and product management: Connect NestJS to the Cloud database dummy .env

### PR DESCRIPTION
**Pull request by alasali1**
Resolves issue #111
This pull request is a dummy .env file that displays to the developers the information required to be able to connect to Belinda's closet database, and interact with it through the front end.

Edit:
This is PR is actually a mistake rooted in a misunderstanding of how the database connects to the front end. This PR describes the steps on how to get the ec2 instance to connect to the devs developer environment on localhost. The database is already connected to the deployed Belinda's closet website and the changes were to be made on the EC2 instance rather than in our codebase on Github. I learned that the database is actually talking to the front end website through SSH on the AWS EC2 instances CLI, whereas I was trying to connect to the db through my own local computer. Now I have a better understanding on what I should have actually done.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM

**Review by heosman — APPROVED** [review]
LGTM!

**Review by IsaacJrTypes — APPROVED** [review]
Thank you for the research and the examples.

**Review by Seiyaroo — APPROVED** [review]
Descriptive but not overly so. Ty for the research. LGTM :)

**Pull request merged**
