### PR TITLE
belindas-closet-nestjs_2_24_admin-role

### LINKED ISSUE #24: BE - Create admin role and functionality
**Make sure the first line is formatted as follows.**\
As a back-end developer, I will want to create an admin role and functionality so that only admins can create/update/delete products. 

**Is your feature request related to a problem? Please describe.**\
Admins need access to CRUD operations but we cannot allow all users access to these operations.

**Describe the solution you'd like**

- [x] Create admin role and functionality so that only admins can create/update/delete products. 
- [x] Use NSC Events' Nest.js repo and our Lead Developer as resources.

**Include link(s) to relevant tutorial(s)**\
[Relevant Folders of NSC Events' Nest.js repo](https://github.com/SeattleColleges/nsc-events-nestjs/tree/main/src)
[Nest.js documentation on authorization](https://docs.nestjs.com/security/authorization)

**Story Points**\
2-4

### PR DESCRIPTION
**Pull request by CourtneyHoppus**
Resolves #24

We want to restrict product creation, updating, and deleting to users with an 'admin' role only.

I implemented the JWT strategy that was already in place, making it so a registered user is required to create, update, or delete a product, which means a valid JWT token is required as an authorization token.
You can generate a JWT token when you either sign-up a user (which creates a user) or login an existing user.
I then implemented a role decorator and guard, so that only a user with an admin role can create, update, or delete a product.

To test:

- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid MongoDB URI string for a database connection and set it as `MONGODB_URI=<your database connection string>` in your `.env`.
- You must set `JWT_SECRET=jwt` in your`.env`.
- You must set an expiry for your JWT Secret, I did `JWT_EXPIRES = 90d` in your `.env`.
- Using the available API calls in the ProductController, use Postman to test.
- Without an Authorization token in the header you should not be able to create(POST), update(PUT), or delete(DELETE) a product making calls to the ProductController.
- Sign-up a new user or login an existing user with 'user' as their role and copy the JWT token.
- Set this token as a Header for Authorization, as seen in the first picture below. You must have the word `Bearer` and a space before your token.
- As a user you still should not be able to create(POST), update(PUT), or delete(DELETE) a product making calls to the ProductController.
- Sign-up a new user or login an existing user with 'admin' as their role and copy the JWT token.
- Set this token as a Header for Authorization, as seen in the first picture below.
- As an admin you should be able to create(POST), update(PUT), or delete(DELETE) a product making calls to the ProductController.
- ** Note: adding a user via path `api/user/add` will add a user to the database, but does not hash the password or return a JWT token, do not use this when testing.**

---------------------------------------

I first implemented that a registered user must be present.

A user with a JWT token can create a product:
authorized_product_creation

A user without a JWT token cannot create a product:
unauthorized_product_creation

I then implemented the role guard so that an admin must be present.

A user with a JWT token with 'admin' status can create a product:
admin_product_creation

A user with a JWT token with a 'user' status cannot create a product:
user_product_creation

Resources used:
[NestJS Docs](https://docs.nestjs.com/security/authorization#basic-rbac-implementation)
Primarily this [article](https://medium.com/@rahulrulz680/manage-role-based-authorization-using-guards-in-nestjs-34b3be412e50) but I did read quite a few more.

### CODE REVIEW

**Comment by tinpham5614** [comment]
Tested POST and PUT requests. Both are working. Thank you!

**Review by tinpham5614 — APPROVED** [review]

**Comment by taylorpapke** [comment]
@CourtneyHoppus @tinpham5614 How do I get the JWT token after creating a user in Postman?

**Comment by taylorpapke** [comment]
> @taylorpapke when you sign-up a user at path `api/auth/signup` you are returned a token. If that token expires, you can login that user at path `api/auth/login` and be returned a token. If you had added a user via path `api/user/add` this will not return a token, you will need to login that user at path `api/auth/login`. A user looks like this: { "name" : "Jane Don't", "email" : "[jane@dont.email](mailto:jane@dont.email)", "role" : "admin", "password" : "passwordString" }

This is what I'm getting when I sign up a user:
Screenshot 2023-11-01 at 1 21 49 PM
and what it shows in nestJS console:
Screenshot 2023-11-01 at 1 23 31 PM
It seems to create a user in my mongoDB:
Screenshot 2023-11-01 at 1 22 19 PM
But how do I log in from here or get token?:
Screenshot 2023-11-01 at 1 28 38 PM

**Comment by CourtneyHoppus** [comment]
I don't know why you're getting that 500 and it still creates a user, that's odd.
@taylorpapke The one screenshot shows the error mentioning an expiration, in my `.env` I set the expires variable to 90 days `JWT_EXPIRES = 90d`, not sure what you have set
Maybe that would help?

**Comment by taylorpapke** [comment]
> I don't know why you're getting that 500 and it still creates a user, that's odd. @taylorpapke The one screenshot shows the error mentioning an expiration, in my `.env` I set the expires variable to 90 days `JWT_EXPIRES = 90d`, not sure what you have set Maybe that would help?

Yes, that worked!

**Comment by taylorpapke** [comment]
Thanks for walking me through the process as it was quite illuminating. 
Here is the admin add new product:
Screenshot 2023-11-01 at 2 13 50 PM
And the user add new product:
Screenshot 2023-11-01 at 2 16 56 PM
I will also highlight that in the examples above, there is the word "Bearer" and a space that must be placed before the token when you add the header authorization key and value:
Screenshot 2023-11-01 at 2 22 42 PM

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
