### PR TITLE
Belindas_nestjs-01-51-route_stubs #51

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves [#51](https://github.com/SeattleColleges/belindas-closet-android/issues/51) 

This PR stubs out potential routes in backend so frontend devs have access to them. Used postman to ensure url's are routing to proper endpoints.

- I had to create a mongo database to quiet the compiler and I had to store the connection string in an .env mongo_uri variable. Although, I don't think it's necessary to do so since the routes visited don't interact with the db, the same issue might persist if a mongo db isn't created. 

- Here's what that would look like an an .env variable after creating the db in mongo:

Screenshot 2023-10-08 at 9 54 23 PM

**user endpoints** 
- Screenshot 2023-10-08 at 9 37 25 PM
- Screenshot 2023-10-08 at 9 37 35 PM
- Screenshot 2023-10-08 at 9 38 53 PM
- Screenshot 2023-10-08 at 9 49 19 PM
- Screenshot 2023-10-08 at 9 49 31 PM

**product endpoints**
- Screenshot 2023-10-08 at 9 43 56 PM
- Screenshot 2023-10-08 at 9 44 06 PM
- Screenshot 2023-10-08 at 9 44 22 PM

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
LGTM, I will leave ultimate approval to Brink, but I don't see any glaring issues currently.

**Review by theGaryLarson — COMMENTED** [review]
@Robel-003 Hey Tin did a lot of this work already. We are standardizing the endpoint definition across repos. See the Api Endpoints in the updated Wiki for this repo. Thanks but you two were doing asynchronous work.

**Comment by Robel-003** [comment]
> @Robel-003 Hey Tin did a lot of this work already. We are standardizing the endpoint definition across repos. See the Api Endpoints in the updated Wiki for this repo. Thanks but you two were doing asynchronous work.

I'm just now seeing the api endpoints wiki. I think I misunderstood the issue thinking that this would be stubbed api endpoints on the backend, but I'm now realizing that it supposed to be template pages on the frontend. Is my understanding correct?

**Comment by brinkbrink** [comment]
Hey @Robel-003  maybe you can work on the issue that Tin is suggesting to be made [here](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/29#discussion_r1353811512):
"I went ahead and fixed the product API endpoints. I will let the PO/PM create issues with the user module, giving other students a chance to learn (user's controller, service, and DTO creation)."
Feel free to create this issue yourself or tag in @theGaryLarson if you want support creating this issue.

**Review by TroyFPV48 — COMMENTED** [review]
Overall it looks great to me that user controller has multiple route handlers. Keep it up!

**Pull request closed without merging**
