### PR TITLE
Belinda's-Closet-NestJS_3_112_Unit-Tests-Product-Controller-and-Service

### LINKED ISSUE #45: USER STORY: Unit Tests for Product Controller and Services Modules
As a developer, I would like to implement some unit tests so that we can automate them during CI/CD to enforce better code quality.

Specific issues:

 Create unit test for the product controller module

 Create unit test for the product service module

Resources:

https://docs.nestjs.com/fundamentals/testing
https://www.youtube.com/watch?v=lih9VT0IZ7U&t=1163s,
https://www.youtube.com/watch?v=dxTuOkgSKh4

### PR DESCRIPTION
**Pull request by CourtneyHoppus**
Resolves #45 

To test:
Pull this branch and open a terminal in the project
Run the tests for the controller by using the terminal command `npm run test products.controller.spec.ts`
Run the tests for the service by using the command `npm run test products.service.spec.ts`

Resources consulted (there were others, I am bad about closing things when they don't work as expected):
[NestJS docs](https://docs.nestjs.com/fundamentals/testing)
[Article](https://www.tomray.dev/nestjs-unit-testing)
[Article](https://betterprogramming.pub/testing-controllers-in-nestjs-and-mongo-with-jest-63e1b208503c)
[Article](https://blog.logrocket.com/unit-testing-nestjs-applications-with-jest/)

### CODE REVIEW

**Comment by taylorpapke** [comment]
I'm not 100% sure that this is exactly related to what you are doing here but noticed that this folder hasn't been copied over and tailored for Product in Belindas-closet-nestjs: https://github.com/SeattleColleges/nsc-events-nestjs/tree/main/test/mock-data

It was part of PR https://github.com/SeattleColleges/nsc-events-nestjs/pull/26 which states that it included unit tests for at least the service controller. Might also be a good idea to reach out to @theGaryLarson for more info about this.

**Comment by CourtneyHoppus** [comment]
Updated the testing for the service to mimic the NSC Events project's activity.

**Comment by CourtneyHoppus** [comment]
I think it would be a good idea to refactor the [product controller](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/controllers/products/products.controller.ts) to mimic the [user controller](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/user/controllers/user/user.controller.ts) in this project and the [activity](https://github.com/SeattleColleges/nsc-events-nestjs/blob/main/src/activity/controllers/activity/activity.controller.ts) and [user controller](https://github.com/SeattleColleges/nsc-events-nestjs/blob/main/src/user/controllers/user/user.controller.ts) in the NSC Events repo.
This entails removing the `try/catch` and `response parameter` from the controller methods.
What do y'all think, @theGaryLarson @taylorpapke @tinpham5614 @brinkbrink @bcko 
I think it will make the projects more consistent and make the testing easier, plus this utilizes NestJS and mongoose and their built-in functionality when throwing errors and handling exceptions.

**Review by taylorpapke — APPROVED** [review]
Tested the following:

npm run test products.controller.spec.ts
Screenshot 2023-11-13 at 2 22 12 PM

npm run test products.service.spec.ts
Screenshot 2023-11-13 at 2 23 05 PM

**Comment by CourtneyHoppus** [comment]
Updated the testing to include the new "delete" functionality in ther Service and Controller.
Added an `.exec()` call to the `delete` method in the service, the testing was complaining and returning strange values.
This now matches the functionality of the rest of the service methods.
Added `extends Document` to the Product Schema to match the other entities and to have the created id available as a property, without this that property isn't exposed properly.
Either as it's own issue or here, I would like to update the exception (and logging) on `createProduct` in the Service.

**Comment by taylorpapke** [comment]
Screenshot 2023-11-14 at 11 53 43 AM
Screenshot 2023-11-14 at 11 54 34 AM

**Review by taylorpapke — APPROVED** [review]

**Review by bcko — APPROVED** [review]
looks good to me

**Pull request merged**
