### PR TITLE
belindas-closet-nestjs_1_22_refactor-user-console.log

### LINKED ISSUE #22: Refactor user console.log to use logger
As a backend developer, I will want to enable logging to view important information about the data transactions occurring.

Is your feature request related to a problem? Please describe.
I'm always frustrated when I can't see why something is not working and console.logs are not completely cutting it.

Describe the solution you'd like
Logs that will more accurately depict what is happening with the data.

Include link(s) to relevant tutorial(s)
https://docs.nestjs.com/techniques/logger

Describe alternatives you've considered
None.

Is this issue related to any other issues?
This issue relates to issue #19 

Additional context\

Image

Story Points
2-4 story points

### PR DESCRIPTION
**Pull request by CourtneyHoppus**
Resolves #22 

This is directly related to my previous PR #32

I set up the logging the same, but as the UserModule is not included in `app.module`:
app module
we cannot make calls to the User Controller.

### CODE REVIEW

**Comment by tinpham5614** [comment]
I've done some manual tests using GET, POST, PATCH methods in User Module. All Logs work.
_Note: User module hasn't completed yet, I think there are some modifications need to be done._
Here is the result for testing:
UserLog

**Comment by taylorpapke** [comment]
@CourtneyHoppus What are the instructions for testing?

**Comment by tinpham5614** [comment]
> @CourtneyHoppus @tinpham5614 What are the instructions for testing?

I added UserModule to app.module.ts and tested with GET, POST, PATCH methods in Postman.
Screenshot 2023-10-26 015927

Endpoint: <http://localhost:3000/api/user>
Json example: 
```
{
    "email": "ronaldo1@gmail.com",
    "name": "ronaldoc",
    "role": "admin"
}
```

**Comment by CourtneyHoppus** [comment]
@tinpham5614 yes, adding the UserModule to app.module will enable calls to the UserController.
The logging you are seeing here is the built in NestJS logging, this PR is built on the previous one, so here the custom logger was not created or added to the app.

**Comment by taylorpapke** [comment]
Tested this and I'm pretty sure I was able to get all of the logs, errors and warnings to show. Here they are a little out of order:
Screenshot 2023-10-27 at 1 32 41 AM
Screenshot 2023-10-27 at 1 48 09 AM
Screenshot 2023-10-27 at 1 51 02 AM
Screenshot 2023-10-27 at 1 57 28 AM

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
