### PR TITLE
Belindas-Closet-nestjs_3_Test-CI-pr-workflow_01

### PR DESCRIPTION
**Pull request by Robel-003**
Testing ci workflow for new pull request

### CODE REVIEW

**Comment by CourtneyHoppus** [comment]
@Robel-003 How should I be testing this?

**Comment by Robel-003** [comment]
> @Robel-003 How should I be testing this?



> @Robel-003 How should I be testing this?

@CourtneyHoppus to test this, in your IDE hop into this [branch](https://github.com/SeattleColleges/belindas-closet-nestjs/tree/feature-111-CI_pr_workflow_test-01). Make a comment, commit the change and push the change up to GitHub. 
It'll take a minute for the workflow to finish and you can also see it running [here](https://github.com/SeattleColleges/nsc-events-android/actions)

**Comment by CourtneyHoppus** [comment]
@Robel-003 looks like I also have to open a PR on the new branch I had to create to push the change to origin.

**Review by CourtneyHoppus — APPROVED** [review]
Tested as directed, made a comment and pushed this [branch](https://github.com/SeattleColleges/belindas-closet-nestjs/tree/testing-PR-43) to the repo and created this [PR](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/54)

**Comment by taylorpapke** [comment]
Didn't notice that the change to the yaml was on this or I would've approved sooner!

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
